# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

SET(LIBTYPE STATIC)
SET(HOST x86_64-linux-musl)
SET(CROSS /home/dirk/cross/x86_64-linux-musl/bin/x86_64-linux-musl-)

SET(CMAKE_C_COMPILER ${CROSS}gcc)

SET(CMAKE_C_FLAGS_DEBUG "-g -O0" CACHE STRING "" FORCE)
SET(CMAKE_C_FLAGS_RELEASE "-O3" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -std=c++1y" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -std=c++1y" CACHE STRING "" FORCE)
SET(CMAKE_EXE_LINKER_FLAGS "-static -static-libgcc -static-libstdc++" CACHE STRING "" FORCE)

SET(CMAKE_FIND_ROOT_PATH $ENV{PKG_DIR})

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)