# this one is important
SET(CMAKE_SYSTEM_NAME Windows)

SET(LIBTYPE STATIC)
SET(HOST x86_64-w64-mingw32)
SET(CROSS x86_64-w64-mingw32-)

SET(CMAKE_C_COMPILER ${CROSS}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS}g++)
SET(CMAKE_RC_COMPILER ${CROSS}windres)

SET(CMAKE_C_FLAGS_DEBUG "-g -O0" CACHE STRING "" FORCE)
SET(CMAKE_C_FLAGS_RELEASE "-O3" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -std=c++1y" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -std=c++1y" CACHE STRING "" FORCE)

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32 $ENV{PKG_DIR})

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)